#!/usr/bin/env bash
set -euo pipefail

# Creates the Keycloak groups and service-account clients this demo needs.
#
# Run this yourself -- it needs your Keycloak admin password, which is deliberately read from
# the environment and never printed. Client secrets are written straight into .env.local
# (gitignored, chmod 600) and are never echoed to the terminal.
#
#   export KEYCLOAK_ADMIN_USER=admin-user
#   export KEYCLOAK_ADMIN_PASSWORD=...        # not stored anywhere
#   ./registry/keycloak-setup.sh
#
# What it creates in realm `solo`:
#
#   Groups
#     support-engineers    the engineer persona -- composes and publishes, cannot approve
#     platform-approvers   the approver persona -- owns policy and the approval gate
#     admins               already exists; used by the automation client
#
#   Clients (all confidential, service accounts on, browser flows off)
#     agentregistry-kagent   agentregistry -> kagent control plane
#     cloudcart-automation   publish.sh and CI -> agentregistry API
#     cloudcart-support-ui   the chat frontend -> agentregistry A2A proxy
#
# Every client gets an explicit Groups mapper. Without one, Keycloak omits group membership
# from client_credentials tokens -- and kagent's roleMapper treats a *missing* Groups claim as
# global.Admin, so an unmapped service account silently becomes an admin.

KEYCLOAK_URL="${KEYCLOAK_URL:-https://keycloak.pintobean.xyz}"
REALM="${REALM:-solo}"
: "${KEYCLOAK_ADMIN_USER:?export KEYCLOAK_ADMIN_USER}"
: "${KEYCLOAK_ADMIN_PASSWORD:?export KEYCLOAK_ADMIN_PASSWORD}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env.local"

api() { # method path [body]
  local method="$1" path="$2" body="${3:-}"
  if [ -n "$body" ]; then
    curl -sS -X "$method" "${KEYCLOAK_URL}/admin/realms/${REALM}${path}" \
      -H "Authorization: Bearer ${ADMIN_TOKEN}" -H 'Content-Type: application/json' -d "$body"
  else
    curl -sS -X "$method" "${KEYCLOAK_URL}/admin/realms/${REALM}${path}" \
      -H "Authorization: Bearer ${ADMIN_TOKEN}"
  fi
}

echo "==> Authenticating to Keycloak..."
# Admin may live in the master realm or in the target realm; try master first.
for tokrealm in master "${REALM}"; do
  ADMIN_TOKEN="$(curl -sS -X POST \
    "${KEYCLOAK_URL}/realms/${tokrealm}/protocol/openid-connect/token" \
    -d grant_type=password -d client_id=admin-cli \
    --data-urlencode "username=${KEYCLOAK_ADMIN_USER}" \
    --data-urlencode "password=${KEYCLOAK_ADMIN_PASSWORD}" \
    | python3 -c 'import json,sys; print(json.load(sys.stdin).get("access_token",""))' 2>/dev/null || true)"
  [ -n "${ADMIN_TOKEN}" ] && { echo "    authenticated via realm '${tokrealm}'"; break; }
done
[ -n "${ADMIN_TOKEN:-}" ] || { echo "ERROR: could not obtain an admin token." >&2; exit 1; }

# --- groups -----------------------------------------------------------------------------
for g in support-engineers platform-approvers admins; do
  existing="$(api GET "/groups?search=${g}&exact=true" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d[0]["id"] if d else "")')"
  if [ -n "$existing" ]; then
    echo "==> Group ${g}: exists"
  else
    api POST "/groups" "{\"name\":\"${g}\"}" >/dev/null
    echo "==> Group ${g}: created"
  fi
done

group_id() {
  api GET "/groups?search=$1&exact=true" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d[0]["id"] if d else "")'
}

# --- clients ----------------------------------------------------------------------------
umask 077
: > "${ENV_FILE}.tmp"
{
  echo "# Generated by registry/keycloak-setup.sh -- gitignored, do not commit."
  echo "# Client secrets for the demo's service accounts."
} >> "${ENV_FILE}.tmp"

make_client() { # clientId group envprefix
  local cid="$1" grp="$2" prefix="$3"

  local uuid
  uuid="$(api GET "/clients?clientId=${cid}" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d[0]["id"] if d else "")')"

  if [ -z "$uuid" ]; then
    api POST "/clients" "$(cat <<JSON
{
  "clientId": "${cid}",
  "protocol": "openid-connect",
  "publicClient": false,
  "serviceAccountsEnabled": true,
  "standardFlowEnabled": false,
  "implicitFlowEnabled": false,
  "directAccessGrantsEnabled": false,
  "description": "cloud-cart-support demo service account"
}
JSON
)" >/dev/null
    uuid="$(api GET "/clients?clientId=${cid}" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d[0]["id"] if d else "")')"
    echo "==> Client ${cid}: created"
  else
    echo "==> Client ${cid}: exists"
  fi

  # Groups mapper -- required, see header note about kagent's admin fallback.
  local has_mapper
  has_mapper="$(api GET "/clients/${uuid}/protocol-mappers/models" \
    | python3 -c 'import json,sys; print(any(m.get("name")=="groups" for m in json.load(sys.stdin)))')"
  if [ "$has_mapper" != "True" ]; then
    api POST "/clients/${uuid}/protocol-mappers/models" "$(cat <<'JSON'
{
  "name": "groups",
  "protocol": "openid-connect",
  "protocolMapper": "oidc-group-membership-mapper",
  "config": {
    "claim.name": "Groups",
    "full.path": "false",
    "access.token.claim": "true",
    "id.token.claim": "true",
    "userinfo.token.claim": "true"
  }
}
JSON
)" >/dev/null
    echo "    added Groups mapper"
  fi

  # Put the client's service-account user in the right group.
  local sa_uid gid
  sa_uid="$(api GET "/clients/${uuid}/service-account-user" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("id",""))')"
  gid="$(group_id "${grp}")"
  if [ -n "$sa_uid" ] && [ -n "$gid" ]; then
    api PUT "/users/${sa_uid}/groups/${gid}" "{}" >/dev/null
    echo "    service account -> group ${grp}"
  fi

  local secret
  secret="$(api POST "/clients/${uuid}/client-secret" "{}" \
    | python3 -c 'import json,sys; print(json.load(sys.stdin).get("value",""))')"
  [ -n "$secret" ] || secret="$(api GET "/clients/${uuid}/client-secret" \
    | python3 -c 'import json,sys; print(json.load(sys.stdin).get("value",""))')"

  {
    echo "${prefix}_CLIENT_ID=${cid}"
    echo "${prefix}_CLIENT_SECRET=${secret}"
  } >> "${ENV_FILE}.tmp"
}

make_client agentregistry-kagent admins  KAGENT_OIDC
make_client cloudcart-automation admins  AUTOMATION
make_client cloudcart-support-ui admins  SUPPORT_UI

{
  echo "KEYCLOAK_URL=${KEYCLOAK_URL}"
  echo "KEYCLOAK_REALM=${REALM}"
  echo "OIDC_ISSUER=${KEYCLOAK_URL}/realms/${REALM}"
} >> "${ENV_FILE}.tmp"

mv "${ENV_FILE}.tmp" "${ENV_FILE}"
chmod 600 "${ENV_FILE}"

echo ""
echo "==> Done. Client secrets written to .env.local (chmod 600, gitignored)."
echo ""
echo "    Next:"
echo "      source .env.local"
echo "      ./registry/get-token.sh            # mints a registry token from the automation client"
echo ""
echo "    Note: all three service accounts are in the 'admins' group for now, which makes them"
echo "    registry superusers. Tighten cloudcart-support-ui once the A2A path is proven, and"
echo "    keep support-engineers / platform-approvers for the two human demo personas."
